# Generated by Django 4.2.4 on 2023-08-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
    ]
