# Generated by Django 4.2.4 on 2023-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_events_created_at_remove_events_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
