apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1    
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1   # Control the pace of the update
      maxUnavailable: 0   # Zero downtime
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: web-service-food:v3  # Update the image version
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
