apiVersion: v1
kind: Service
metadata:
  name: django-nodeport-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000  # Specify a port in the 30000-32767 range
